In [110]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [29]:
df = pd.read_csv("hiring.csv")

In [31]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [33]:
word_to_number = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, 
    "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11, "twelve": 12,
    "thirteen": 13, "fourteen": 14, "fifteen": 15, "sixteen": 16, "seventeen": 17,
    "eighteen": 18, "nineteen": 19, "twenty": 20, "twenty one": 21, "twenty two": 22,
    "twenty three": 23, "twenty four": 24, "twenty five": 25, "twenty six": 26,
    "twenty seven": 27, "twenty eight": 28, "twenty nine": 29, "thirty": 30,
    "thirty one": 31, "thirty two": 32, "thirty three": 33, "thirty four": 34,
    "thirty five": 35, "thirty six": 36, "thirty seven": 37, "thirty eight": 38,
    "thirty nine": 39, "forty": 40, "forty one": 41, "forty two": 42, "forty three": 43,
    "forty four": 44, "forty five": 45, "forty six": 46, "forty seven": 47, "forty eight": 48,
    "forty nine": 49, "fifty": 50
}
# Function to convert worded numbers to actual numbers
def convert_to_number(x):
    if isinstance(x, str):
        x = x.lower().strip()  # Normalize the string (lowercase, remove extra spaces)
        return word_to_number.get(x, np.nan)  # Return the mapped number, or NaN if not found
    else:
        return x  # If it's not a string, return the value as is

df["experience"] = df["experience"].apply(convert_to_number)


In [163]:
df.loc[0,'experience'] = 0
df.loc[1,'experience'] = 0
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [137]:
x = df["experience"].median()

In [139]:
x

4.0

In [141]:
df["experience"] = df["experience"].fillna(x)

In [161]:
y = math.floor(df['test_score(out of 10)'].mean())
y

7

In [145]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(y)

In [182]:
df.loc[6,"test_score(out of 10)"] = 7
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [184]:
reg = linear_model.LinearRegression()
X = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]
y = df['salary($)']

In [186]:
reg.fit(X, y)  # Ensure no errors here
print("Model fitted successfully.")

Model fitted successfully.


In [188]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [190]:
reg.intercept_

14992.651446693126

In [192]:
reg.predict([[2,9,6]])

C:\Users\ranveer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [194]:
reg.predict([[12,10,10]])

C:\Users\ranveer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])